# Generated by Django 4.0.4 on 2022-06-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='camp_id',
        ),
        migrations.DeleteModel(
            name='Camp',
        ),
    ]
