# Generated by Django 4.0.4 on 2022-06-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_item_camp_id_delete_camp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('camp_start', models.CharField(max_length=100)),
                ('camp_end', models.CharField(max_length=100)),
            ],
        ),
    ]
