# Generated by Django 4.0.4 on 2022-06-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_camp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
