# Generated by Django 4.0.4 on 2022-06-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_purpose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
