# Generated by Django 4.0.4 on 2022-06-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='purpose',
            new_name='purpose_id',
        ),
    ]
