# Generated by Django 4.0.4 on 2022-06-23 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_rename_purpose_item_purpose_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='purpose_id',
        ),
        migrations.DeleteModel(
            name='Purpose',
        ),
    ]
