# Generated by Django 4.0.4 on 2022-06-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_purpose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
