# Generated by Django 4.0.4 on 2022-06-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
