# Generated by Django 4.0.4 on 2022-06-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_category_remove_item_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
