# Generated by Django 4.0.4 on 2022-06-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CHEE',
        ),
    ]
