# Generated by Django 4.0.4 on 2022-06-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_chee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CHEE',
            new_name='Staff',
        ),
    ]
