# Generated by Django 4.0.4 on 2022-07-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_stafffeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffLeave',
        ),
    ]
