# Generated by Django 4.0.4 on 2022-07-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_itemrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemrequest',
            old_name='date_of_purchase',
            new_name='date_of_request',
        ),
    ]
