# Generated by Django 4.0.4 on 2022-07-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_itemrequest_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemRequest',
        ),
    ]
