# Generated by Django 4.0.4 on 2022-07-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='location_id',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
