# Generated by Django 4.0.4 on 2022-07-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='manufacture',
            field=models.CharField(blank='True', max_length=100, null='True'),
        ),
    ]
