# Generated by Django 3.2.6 on 2023-04-26 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_auto_20230426_1133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='Out',
        ),
    ]
