# Generated by Django 3.2.6 on 2023-05-11 08:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='medicine',
            name='drug_strength',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.timezone, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispense_quantity', models.PositiveIntegerField(default='1', null=True)),
                ('taken', models.CharField(blank=True, max_length=300, null=True)),
                ('medicine_ref_no', models.CharField(blank=True, max_length=300, null=True)),
                ('dispense_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('drug_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.medicine')),
            ],
        ),
    ]
