# Generated by Django 3.2.6 on 2023-06-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_auto_20230608_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispense',
            old_name='taken',
            new_name='issued_to',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='issued_to',
        ),
    ]
