# Generated by Django 3.2.6 on 2023-06-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0063_auto_20230608_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='bill_no',
            field=models.IntegerField(default=1),
        ),
    ]
