# Generated by Django 3.2.6 on 2023-06-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_medicine_bill_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispense',
            old_name='medicine_ref_no',
            new_name='bill_no',
        ),
        migrations.RenameField(
            model_name='dispense',
            old_name='drug_id',
            new_name='medicine_id',
        ),
    ]
