# Generated by Django 3.2.6 on 2023-06-11 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0065_auto_20230611_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispense',
            name='medicine_id',
        ),
        migrations.AddField(
            model_name='dispense',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.medicine'),
        ),
    ]
