# Generated by Django 3.2.6 on 2023-06-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_auto_20230611_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispense',
            old_name='medicine',
            new_name='medicine_id',
        ),
    ]
