# Generated by Django 3.2.6 on 2023-06-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_rename_medicine_dispense_medicine_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispense',
            old_name='medicine_id',
            new_name='medicine',
        ),
    ]
