# Generated by Django 3.2.6 on 2023-06-12 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_auto_20230612_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField(default=1)),
                ('medicine_name', models.CharField(max_length=100)),
                ('drug_type', models.CharField(blank='True', max_length=100, null='True')),
                ('drug_price', models.FloatField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('quantity_instrip', models.IntegerField(default=1)),
                ('receive_quantity', models.CharField(max_length=100)),
                ('reorder_level', models.IntegerField(blank='True', default='0', null='True')),
                ('manufacture', models.CharField(blank='True', max_length=100, null='True')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('drug_strength', models.CharField(blank=True, max_length=10, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(null=True)),
                ('remarks', models.CharField(blank='True', max_length=100, null='True')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispense_quantity', models.PositiveIntegerField(default='1', null=True)),
                ('issued_to', models.CharField(blank=True, max_length=300, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=300, null=True)),
                ('dispense_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.medicine')),
            ],
        ),
    ]
