# Generated by Django 3.2.6 on 2023-06-12 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0070_dispense_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='quantity_instrip',
            new_name='quantity_in_strip',
        ),
    ]
