# Generated by Django 3.2.6 on 2023-06-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0073_alter_medicine_quantity_in_strip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='quantity_in_strip',
            field=models.IntegerField(blank='True', default=1, null='True'),
        ),
    ]
