# Generated by Django 3.2.6 on 2023-06-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0074_alter_medicine_quantity_in_strip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleave',
            name='to_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
