# Generated by Django 4.2.2 on 2023-07-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0076_leavebalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='annual_leave_balance',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='lieu_leave_balance',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='sick_leave_balance',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='annual_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='lieu_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='sick_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='StaffLeave',
        ),
    ]
