# Generated by Django 4.2.2 on 2023-07-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0079_staff_annual_leave_staff_lieu_leave_staff_sick_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleave',
            name='leave_type',
            field=models.CharField(choices=[('aanual leave', 'Annual Leave'), ('sick leave', 'Sick Leave'), ('lieu leave', 'Lieu Leave')], max_length=100),
        ),
    ]
