# Generated by Django 4.2.2 on 2023-07-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0081_alter_staffleave_leave_type_delete_leavebalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='annual_leave',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lieu_leave',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sick_leave',
            field=models.FloatField(default=0),
        ),
    ]
