# Generated by Django 4.2.2 on 2023-07-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0086_alter_notification_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
