# Generated by Django 4.2.2 on 2023-07-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0088_medicine_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='is_read',
        ),
    ]
