# Generated by Django 4.2.2 on 2023-07-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0089_remove_medicine_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffleave',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
