# Generated by Django 4.2.2 on 2023-07-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0090_rename_staff_id_staffleave_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleave',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffleave',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
