# Generated by Django 4.2.2 on 2023-07-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0091_alter_staffleave_from_date_alter_staffleave_to_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffleave',
            old_name='staff',
            new_name='staff_id',
        ),
        migrations.AlterField(
            model_name='staffleave',
            name='leave_type',
            field=models.CharField(choices=[('ANNUAL_LEAVE', 'Annual Leave'), ('SICK_LEAVE', 'Sick Leave'), ('LIEU_LEAVE', 'Lieu Leave')], max_length=100),
        ),
    ]
