# Generated by Django 4.2.2 on 2023-07-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0092_rename_staff_staffleave_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='annual_leave',
            field=models.FloatField(default=16.0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lieu_leave',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sick_leave',
            field=models.FloatField(default=12.0),
        ),
    ]
