# Generated by Django 4.2.2 on 2023-07-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0093_alter_staff_annual_leave_alter_staff_lieu_leave_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='admin',
            new_name='user',
        ),
    ]
