# Generated by Django 4.2.2 on 2023-07-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0095_alter_staff_annual_leave_alter_staff_lieu_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleave',
            name='leave_type',
            field=models.CharField(choices=[('ANNUAL_LEAVE', 'Annual'), ('SICK_LEAVE', 'Sick Leave'), ('LIEU_LEAVE', 'Lieu Leave')], max_length=100),
        ),
    ]
