# Generated by Django 4.2.2 on 2023-07-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0097_alter_staffleave_leave_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='annual_leave',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='lieu_leave',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='sick_leave',
        ),
    ]
