# Generated by Django 4.2.2 on 2023-07-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0098_remove_staff_annual_leave_remove_staff_lieu_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='annual_leave',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='lieu_leave',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='sick_leave',
            field=models.FloatField(default=0),
        ),
    ]
