# Generated by Django 4.2.2 on 2023-07-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0099_staff_annual_leave_staff_lieu_leave_staff_sick_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='annual_leave',
            field=models.FloatField(default=18.0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lieu_leave',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sick_leave',
            field=models.FloatField(default=12.0),
        ),
    ]
