# Generated by Django 4.2.2 on 2023-08-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0100_alter_staff_annual_leave_alter_staff_lieu_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispense',
            name='issued_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.staff'),
        ),
    ]
