# Generated by Django 4.2.2 on 2023-08-01 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0102_rename_issued_to_dispense_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispense',
            name='staff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.staff'),
        ),
    ]
