# Generated by Django 4.2.2 on 2023-08-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0104_remove_dispense_staff_id_dispense_issued_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dispense',
        ),
    ]
