# Generated by Django 4.2.2 on 2023-08-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0107_alter_dispense_dispense_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dispense',
        ),
    ]
