# Generated by Django 4.2.2 on 2023-08-01 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0108_delete_dispense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispense_quantity', models.PositiveIntegerField(max_length=5, null=True)),
                ('issued_to', models.CharField(blank=True, max_length=300, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=300, null=True)),
                ('dispense_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.medicine')),
            ],
        ),
    ]
