# Generated by Django 4.2.2 on 2023-08-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0109_dispense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispense',
            name='dispense_quantity',
            field=models.PositiveIntegerField(default='1', null=True),
        ),
    ]
