# Generated by Django 4.2.2 on 2023-08-01 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0110_alter_dispense_dispense_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispense',
            name='issued_to',
        ),
        migrations.AddField(
            model_name='dispense',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.staff'),
        ),
    ]
