# Generated by Django 4.2.2 on 2023-08-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0111_remove_dispense_issued_to_dispense_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispense',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='dispense',
            name='issued_to',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
