# Generated by Django 4.2.2 on 2023-08-15 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0112_remove_dispense_staff_id_dispense_issued_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='annual_leave',
            field=models.FloatField(default=18.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lieu_leave',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sick_leave',
            field=models.FloatField(default=12.0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'staff')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stafffeedback',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffleave',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
