# Generated by Django 4.2.2 on 2023-08-15 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0113_customuser_annual_leave_customuser_lieu_leave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='annual_leave',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lieu_leave',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sick_leave',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'staff')], default=1, max_length=50),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_leave', models.FloatField(default=18.0)),
                ('sick_leave', models.FloatField(default=12.0)),
                ('lieu_leave', models.FloatField(default=3.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.staff'),
        ),
        migrations.AlterField(
            model_name='stafffeedback',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.staff'),
        ),
        migrations.AlterField(
            model_name='staffleave',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.staff'),
        ),
    ]
