# Generated by Django 4.2.2 on 2023-08-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0114_remove_customuser_annual_leave_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemRequest',
        ),
    ]
